services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  postgres-order:
    image: postgres:16
    container_name: postgres-order
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    volumes:
      - pg_order_data:/var/lib/postgresql/data

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inv_user
      POSTGRES_PASSWORD: inv_pass
    volumes:
      - pg_inventory_data:/var/lib/postgresql/data

volumes:
  pg_order_data:
  pg_inventory_data:
